// Organization mapping for apps
const APP_TO_ORGANIZATION = {
  // Seven Mountains
  'froggy-98': 'seven_mountains',
  'wowy-radio': 'seven_mountains',
  'wink-106': 'seven_mountains',
  'willie-radio': 'seven_mountains',
  'this-bigfoot-country': 'seven_mountains',
  'the-big-pig': 'seven_mountains',
  'poco-103': 'seven_mountains',
  'my-froggy-valley': 'seven_mountains',
  'merf-radio': 'seven_mountains',
  'love-my-bigfoot': 'seven_mountains',
  'froggy-95-5': 'seven_mountains',
  'bigfoot-country-radio': 'seven_mountains',
  'beaver-96-7': 'seven_mountains',
  'radio-novo': 'seven_mountains',
  'i-love-froggy': 'seven_mountains',
  '935-sbg': 'seven_mountains',
  'the-bus-rocks': 'seven_mountains',
  'hanna-radio': 'seven_mountains',
  'love-my-froggy': 'seven_mountains',
  'listen-to-froggy': 'seven_mountains',
  'the-met-rocks': 'seven_mountains',
  'my-bigfoot-country': 'seven_mountains',
  'bigfoot-country': 'seven_mountains',
  'wilbur-radio': 'seven_mountains',
  'passport-radio-ky': 'seven_mountains',
  'froggy-radio-ky': 'seven_mountains',
  'pop-radio-931': 'seven_mountains',
  'wuhu-107': 'seven_mountains',
  'my-pop-radio': 'seven_mountains',
  'wxil-radio': 'seven_mountains',

  // Seven Mountains 3
  'waly-radio': 'seven_mountains_3',
  'rocky-1049': 'seven_mountains_3',
  'this-is-pop-radio': 'seven_mountains_3',
  'big-froggy-101': 'seven_mountains_3',
  'passport-radio-pa': 'seven_mountains_3',
  'mega-rock-pa': 'seven_mountains_3',
  'rocky-99-johnstown': 'seven_mountains_3',
  'key-965': 'seven_mountains_3',
  'its-pop-radio': 'seven_mountains_3',
  '3wz-radio': 'seven_mountains_3',
  'bigfoot-country-legends': 'seven_mountains_3',
  'bigfoot-legends-radio': 'seven_mountains_3',

  // Seven Mountains 4
  'bigfoot-legends-ky': 'seven_mountains_4',
  'hear-the-goat': 'seven_mountains_4',
  'the-point-rocks': 'seven_mountains_4',
  'big-hits-bg': 'seven_mountains_4',
  'wingz-93': 'seven_mountains_4',
  'twin-tiers-magic': 'seven_mountains_4',
  'my-radio-jamz': 'seven_mountains_4',
  'my-cool-radio': 'seven_mountains_4',
  'bigfoot-legends-ny': 'seven_mountains_4',
  'pop-radio-ky': 'seven_mountains_4',
  'big-oly-radio': 'seven_mountains_4',
  'goat-rock-radio': 'seven_mountains_4',

  // Seven Mountains 5
  'big-lewie': 'seven_mountains_5',
  'woga-radio': 'seven_mountains_5',
  'my-rocky-radio': 'seven_mountains_5',
  'wuzz-radio': 'seven_mountains_5',
  'i-love-pop-radio': 'seven_mountains_5',
  'listen-to-pop': 'seven_mountains_5',
  'bear-radio-rocks': 'seven_mountains_5',
  'my-goat-rocks': 'seven_mountains_5',
  'its-willie-radio': 'seven_mountains_5',
  'pop-radio-1035': 'seven_mountains_5',
  'bigfoot-poconos': 'seven_mountains_5',
  'bigfoot-legends-pa': 'seven_mountains_5',

  // NRW
  'radio-91-2': 'nrw',
  'antenne-unna': 'nrw',
  'radio-vest': 'nrw',
  'radio-rsg': 'nrw',
  'radio-bochum': 'nrw',
  'radio-duisburg': 'nrw',
  'radio-escher-lippe': 'nrw',
  'radio-essen': 'nrw',
  'radio-hagen': 'nrw',
  'radio-herne': 'nrw',
  'radio-kw': 'nrw',
  'radio-mulheim': 'nrw',
  'radio-oberhausen': 'nrw',
  'radio-sauerland': 'nrw',
  'radio-siegen': 'nrw',
  'radio-hellweg': 'nrw',
  'radio-lippewelle': 'nrw',
  'radio-mk': 'nrw',
  'radio-berg': 'nrw',
  'radio-bonn': 'nrw',
  'radio-erft': 'nrw',
  'radio-euskirchen': 'nrw',
  'radio-koln': 'nrw',
  'radio-leverkusen': 'nrw',
  'radio-rur': 'nrw',

  // Alpha Media
  'san-antonio': 'alpha_media',
  'wiil-rock': 'alpha_media',
  'djx': 'alpha_media',
  'the-bull': 'alpha_media',
  'kink': 'alpha_media',
  'the-game': 'alpha_media',
  'b965': 'alpha_media',
  'ktsa': 'alpha_media',
  'kxl': 'alpha_media',
  'live-95-5': 'alpha_media',
  'we-102-9': 'alpha_media',
  'bay-country': 'alpha_media',
  'free-country': 'alpha_media',

  // Others
  'q-rated': 'others',
  'ibiza-sonica': 'others',
  'antenne-sylt': 'others',
  'antenne-vorarlberg': 'others',
  'megamix': 'others',
  'globo-vintage': 'others',
  'radio-globo': 'others',
  'radio-romanista': 'others',
  'radio21': 'others',
  'the-wolf': 'others',
  'rockland-radio': 'others',
  'suisse-podcast': 'others',
  'wtts': 'others',
  'bloomingtons-voice': 'others',
  'the-quarry': 'others',
  'veneto-24': 'others',
  'b1streaming': 'others',
  'onefm': 'others',
  'lfm': 'others',
  'radio-lac': 'others',
  'rouge': 'others',
  'sunshine-live': 'others',
  'sunshine-live-at': 'others',
  'listen-boise': 'others',
  'fly-98-5': 'others',
  'hot-93-7': 'others',
  'that-station': 'others',
  'my105-dj-radio': 'others',
  'radio-2go': 'others',
  'hotel-music': 'others',
  'inferno-radio': 'others',
  'gold-play': 'others',
  'my-country': 'others',
  'the-breeze': 'others',
  'radio-top': 'others',
  'majic-95-1': 'others',
  'classic-hits': 'others',
  'radio-fondue': 'others',
  'alt-99-5': 'others',
  'urban-radio': 'others',
  'magic-92-5': 'others',
  'babboleo': 'others',
  '96-9-wink-fm': 'others',
  'radijas': 'others',
  'rundfunk': 'others',
  'listen-sunny-coast': 'others',
};

export function getOrganizationForApp(appName) {
  // Check exact match first
  if (APP_TO_ORGANIZATION[appName]) {
    return APP_TO_ORGANIZATION[appName];
  }
  
  // Check case-insensitive match
  const lowerAppName = appName.toLowerCase();
  for (const [app, org] of Object.entries(APP_TO_ORGANIZATION)) {
    if (app.toLowerCase() === lowerAppName) {
      return org;
    }
  }
  
  // Default to 'Unknown' if no mapping found
  return 'Unknown';
}